sudo: enabled 

language: python

python:
  - "3.6"

services:
  - docker

install:
  - pip3 install -r requirements.txt
  - docker build -t frudo .
  - docker run -d -p 127.0.0.1:80:80 --name frudo frudo
  - cd project
  - ./new_db.sh
  - python3 manage.py runserver

script:
  - docker ps | grep -q frudo
  - python Django/manage.py runserver
